{{- if and .Values.enrollment.token (not .Values.enrollment.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exitmesh.enrollmentSecretName" . }}
  namespace: {{ .Values.namespaces.coordinator }}
  labels:
    {{- include "exitmesh.labels" (dict "ctx" . "component" "coordinator") | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.enrollment.token | b64enc | quote }}
{{- end }}
