apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "exitmesh.coordinatorName" . }}
  namespace: {{ .Values.namespaces.coordinator }}
  labels:
    {{- include "exitmesh.labels" (dict "ctx" . "component" "coordinator") | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "exitmesh.nodeName" . }}
  namespace: {{ .Values.namespaces.node }}
  labels:
    {{- include "exitmesh.labels" (dict "ctx" . "component" "node") | nindent 4 }}
automountServiceAccountToken: false
